### ISSUE TITLE
DHT and V3 protocol

### ISSUE THREAD

**Issue by benoitc** [telehash/telehash.org#120]
Is it described somewhere? What are the plan for it?

**Comment by quartzjer** [comment]
I apologize that the v3 draft docs haven't made this more clear, I have a backlog of markdowning to do this weekend and this is now the number-one thing to add/clarify right away.

The early TLDR is that the DHT was completely split out in v3, so that the core can focus on the end-to-end encryption, and be able to use different private and/or public routing mechanisms (like a DHT).  I have most of the v2 DHT work standing by in https://github.com/quartzjer/dotPublic until v3 core is stable.

**Comment by benoitc** [comment]
makes sense. thanks for your answer!
