### ISSUE TITLE
Bundled Spec

### ISSUE THREAD

**Issue by quartzjer** [telehash/telehash.org#143]
It would be great to have a "make pdf" that can turn the v3 markdown files into a combined spec.  cc @temas

**Comment by bachp** [comment]
I have some experience with [mkdocs](http://www.mkdocs.org/) but it only outputs html.
[Sphinx](http://sphinx-doc.org/) allows to produce some nice [pdfs](http://sphinx-doc.org/sphinx.pdf) but it is using reStructuredText and not markdown.

Then there is [Pandoc](http://johnmacfarlane.net/pandoc/) that allows conversion between many formats, but I have not used it much.

**Comment by bachp** [comment]
I did some experiment with sphinx.
To do this I converted from Markdown to restructured text using Pandoc.
Then is used Sphinx to create a part of the spec.

Results:
[PDF from Sphinx using Latex](https://www.dropbox.com/s/plk9a64ek3bzsom/Telehash-sphinx_latex.pdf?dl=0)
[PDF from Sphinx using rst2pdf](https://www.dropbox.com/s/k4ye2cwnb90qe1t/Telehash-sphinx_rst2pdf.pdf?dl=0)

The sphinx project could also be uploaded to [Read the Docs](https://readthedocs.org/).

**Comment by quartzjer** [comment]
That turned out better than I expected, very cool!

Is there a way to automate this, perhaps make a `v3/build/` dir with a Makefile, so that I could help tweak/improve it?

**Comment by bachp** [comment]
Sure I can add that.
However I think there are still some issues when converting from Markdown to reStructuredText like links between documents that are not correctly working.
So in the long therm if we want to go the sphinx route it might be worth to switch to rst. It also has some more advanced features like glossary term definitions which would address the `JSON` vs **keyword** problem mentioned in #128.

**Comment by quartzjer** [comment]
poke @temas to chime in too, since he went through a markdown->pdf project last year and should have some practical thoughts :)

**Comment by temas** [comment]
Just a note, I'll drop my workflow in here tomorrow.

**Comment by temas** [comment]
So, I just did a book over the summer and the process used was such:

* Original text was written in markdown, as the lowest common denominator agreement with the other author.
* MD was converted to HTML with a focus on the HTML being compatible with [HTMLBook](https://github.com/oreillymedia/htmlbook).
* Custom CSS was created for the look and design of the book
* The HTML and CSS was processed using Prince to generate the final forms.

I honestly can't remember what tool we used to do md -> html because we only had to do this step once in our case.  We tweaked from the HTML after that.  The biggest time sink is the CSS to get it to a style that you like.  Overall it was a very pleasant process.

In our use case here we'd need some good focus on the conversion process md->html because we don't want to touch the HTML intermediate.  This is definitely something I can put some time on unless @bachp is interested on running with it.  I'm not married to any particular process either, just want to get it done.

**Comment by bachp** [comment]
I didn't know HTMLBook, but it looks interesting.
The reason I had a look at sphinx is because there were a number of nice documentations written with it (python, cmake, readthedocs) and it is able to produce many output formats (html, latex,pdf,epub,...). However I didn't use it peronally for more than my experiments. So I'm open.

Some problems I see, mabe you @temas can tell how you soved that with HTMLBook.

- Crossreferences did not work correctly after the conversion, because they referred to .md filey
- Organization of files so that it makes sense to read then in a linear fashion (book)
- Limited features of markdown (no glossary, no term definition)

**Comment by bachp** [comment]
I didn't know HTMLBook, but it looks interesting.
The reason I had a look at sphinx is because there were a number of nice documentations written with it (python, cmake, readthedocs) and it is able to produce many output formats (html, latex,pdf,epub,...). However I didn't use it peronally for more than my experiments. So I'm open.

Some problems I see, mabe you @temas can tell how you soved that with HTMLBook.

- Crossreferences did not work correctly after the conversion, because they referred to .md filey
- Organization of files so that it makes sense to read then in a linear fashion (book)
- Limited features of markdown (no glossary, no term definition)

**Comment by quartzjer** [comment]
If any of the md->html tools support the [foo][] footnote style references better I'd be happy to start using a different syntax to make linking easier?

**Comment by bachp** [comment]
[Pandoc](http://johnmacfarlane.net/pandoc/) is able to understand the footnote syntax.

I will try to implement a solution using the following pipeline:

```
                                                   /==> Browsable on Read the Docs
Markdown ==[Pandoc]==> reStructuredText ==[Sphinx] ===> PDF document
                                                   \==> EPUB or Plaintext
```

I belive this would cover the most common use cases: Online and searchable on [Read the Docs](http://read-the-docs.readthedocs.org/en/latest/) and offline as a PDF.
You can then tell me if this would satisfy the need

**Comment by quartzjer** [comment]
Sounds cool, I expect we'll have to do some significant reorg/formatting cleanup of all the markdown before v3 stable just for these kinds of purposes, so feel free to share anything you learn that will make it easier along the way, thanks!

**Comment by bachp** [comment]
Here are my first results you can have a look at it [here](https://github.com/bachp/telehash.org/tree/sphinx).

The resulting [Read the Docs](http://telehashorg.readthedocs.org/en/latest/).
The resulting [PDF](https://www.dropbox.com/s/p075xqa0e4ct1d2/Telehash-sphink-branch.pdf?dl=0).

There are some open issues that still need to be solved:

1. Links between documents are not working. Sphinx uses special rST directives `:doc:` for that :-(
2. I was not able to do the Mardkdown -> reStructuredText conversion on Read the docs. (That's why I checked in the resulting .md.rst files)
3. The files need to be structured in a [`toctree`](http://sphinx-doc.org/markup/toctree.html#directive-toctree)

In order to solve issue 1. there is some post processing necessary after the conversion.
Issue 2 I don't know how to solve. One possibility would be to not use read the docs build the html on [travis-ci](https://travis-ci.org) and host it somewhere else, but that's a lot less comfortable.

**Comment by bachp** [comment]
Just to make sure. What is the expectation for this issue?
Just to create a PDF? Or also have the flexibility to have a alternative more approachable form of the documentation then just browsing github?

**Comment by quartzjer** [comment]
I'd like to keep the source docs all in markdown, but if there was an automated way to build "prettier" static html as well as a pdf from the markdown that would be amazing, I just don't know if it's really possible or easy, or what we have to do to the markdown to make it easier too.

I chatted w/ temas and he has some thoughts as soon as he's through c# debugging :)
