### ISSUE TITLE
slack for collab/dev/chat

### ISSUE THREAD

**Issue by quartzjer** [telehash/telehash.org#151]
I've created a telehash team at http://telehash.slack.com and am going to set up an auto-invite form like socket.io/slack (https://github.com/outsideris/slack-invite-automation), but until then anyone can email me for an invite!

**Comment by jaytaph** [comment]
Hi Jeremy,

FYI, slack has changed some things concerning using generated api-keys in combination with the undocumented invite API call. If things doesn't seem to work with a generated key, best thing is to check your personal slack admin invitation page, and fetch the key that is in use there (they will use the same API call, but with a different key). This key will work most definately..   It might save you some time (since our slack channels are working on the same principle, until they tried to stopped this mass-invite functionality)

**Comment by dvanduzer** [comment]
+1

**Comment by quartzjer** [comment]
Also just to be handy the current (temporary until site refresh) invite form is at http://6.telehash.org:3000
